PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

select distinct ?value {
  ?uri a $type .
  ?uri $property ?x.

  bind (datatype(?x) as ?datatypeValue)
  bind (coalesce(?datatypeValue, rdf:langString) as ?value)
}
order by ?value
