@startuml
class "MyShapemaxExclusive" 
"MyShapemaxExclusive" : age : integer(65)

note as N1
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix schema: <http://schema.org/> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix ex: <http://example.org/> .

ex:MyShapemaxExclusive a sh:NodeShape ;
sh:targetClass ex:Person ;
sh:property [
   sh:path ex:age ;
   sh:maxExclusive 65 ;
   sh:datatype xsd:integer ;
] .
end note

hide circle
hide empty members
@enduml

========================================================

@startuml
class "MyShapemaxExclusive" 
"MyShapemaxExclusive" : ex:age : integer
"MyShapemaxExclusive" : +maxExclusive(int)

note as N1
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix schema: <http://schema.org/> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix ex: <http://example.org/> .

ex:MyShapemaxExclusive a sh:NodeShape ;
sh:targetClass ex:Person ;
sh:property [
   sh:path ex:age ;
   sh:maxExclusive 65 ;
   sh:datatype xsd:integer ;
] .
end note

hide circle
hide empty members
@enduml