@startuml
class "ex:MyShape" 
"ex:MyShape" : name : string[1..3]

note as N1
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix schema: <http://schema.org/> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix ex: <http://example.org/> .

ex:MyShapeminmaxCount a sh:NodeShape ;
sh:targetClass ex:Person ;
sh:property[
  sh:path ex:name ;
  sh:minCount 1 ;
  sh:maxCount 3 ;
  sh:datatype xsd:string
] .
end note

hide circle
hide empty members
@enduml