# SPRING DOC OPEN API PROPERTIES
# Permet d'inclure les endpoints ModelAndView par défaut à false
springdoc.model-and-view-allowed=false
# Permet d'indiquer les packages à scanner par springdoc
springdoc.packages-to-scan=fr.sparna.rdf.shacl.shaclplay.doc,fr.sparna.rdf.shacl.shaclplay.draw
# springdoc.writer-with-order-by-keys default = false Enable a deterministic/alphabetical ordering.
springdoc.writer-with-order-by-keys=true
server.forward-headers-strategy=framework