@startuml
class "ex:MyShapeequals"
"ex:MyShapeequals" : ex:firstname(= ex:givenName)

note as N1
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix schema: <http://schema.org/> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix ex: <http://example.org/> .

ex:MyShapeequals a sh:NodeShape ;
sh:targetClass ex:Person ;
sh:property [
   sh:path ex:firstname ;
   sh:equals ex:givenName ;
] .
end note

hide circle
hide empty members
@enduml