@startuml
class "ex:MyShape"
"ex:MyShape" : ex:name : string[1..2]

note as N1
@prefix ex: <http://example.org/ns#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .

ex:MyShape a sh:NodeShape ;
sh:targetClass ex:Person ;
sh:close true;
sh:ignoredProperties(rdf:type);
sh:property [
   sh:path ex:name ;
   sh:minCount 1 ;
   sh:maxCount 2 ;
   sh:datatype xsd:string ;
] .
end note

hide circle
hide empty members
@enduml